<?php
// De versie moet gelijk zijn met het versie nummer in de pleegoudersupport
define('PLEEGOUDERSUPPORT_VERSION', '0.0.1');
// Minimum required Wordpress version for this plugin
define('PLEEGOUDERSUPPORT_REQUIRED_WP_VERSION', '4.0');
define('PLEEGOUDERSUPPORT_PLUGIN_BASENAME', plugin_basename(PLEEGOUDERSUPPORT_PLUGIN));
define('PLEEGOUDERSUPPORT_PLUGIN_NAME', trim(dirname(PLEEGOUDERSUPPORT_PLUGIN_BASENAME), '/'));
// Folder structure
define('PLEEGOUDERSUPPORT_PLUGIN_DIR', untrailingslashit(dirname(PLEEGOUDERSUPPORT_PLUGIN)));
define('PLEEGOUDERSUPPORT_PLUGIN_INCLUDES_DIR', PLEEGOUDERSUPPORT_PLUGIN_DIR . '/includes');
define('PLEEGOUDERSUPPORT_PLUGIN_INCLUDES_VIEWS_DIR', PLEEGOUDERSUPPORT_PLUGIN_INCLUDES_DIR . '/views');
define('PLEEGOUDERSUPPORT_PLUGIN_MODEL_DIR', PLEEGOUDERSUPPORT_PLUGIN_INCLUDES_DIR . '/model');
define('PLEEGOUDERSUPPORT_PLUGIN_STYLE_DIR', PLEEGOUDERSUPPORT_PLUGIN_INCLUDES_DIR . '/style');
define('PLEEGOUDERSUPPORT_PLUGIN_DOCUMENTEN_DIR', PLEEGOUDERSUPPORT_PLUGIN_INCLUDES_DIR . '/documenten');
define('PLEEGOUDERSUPPORT_PLUGIN_DATABASE_DIR', PLEEGOUDERSUPPORT_PLUGIN_INCLUDES_DIR . '/database');
define('PLEEGOUDERSUPPORT_PLUGIN_ADMIN_DIR', PLEEGOUDERSUPPORT_PLUGIN_DIR . '/admin');
define('PLEEGOUDERSUPPORT_PLUGIN_ADMIN_VIEWS_DIR', PLEEGOUDERSUPPORT_PLUGIN_ADMIN_DIR . '/views');


?>